# AI Coding
oc: opencode
occ: opencode --continue
cx: codex
cxx: codex --last
cc: claude --model claude-opus-4-6 --permission-mode bypassPermissions
  --allow-dangerously-skip-permissions --dangerously-skip-permissions
ccc: cc --continue

# NPM
r: node --run
nid: ni -D

# Toolchain
j: just
m: make
fl: fvm flutter

# PHP
pa: php artisan
pas: php artisan serve

# Git
gc: git checkout
gcn: git checkout -b
gds: git diff --stat

# GitHub CLI
ghv: gh repo view
ghw: gh repo view --web

# Docker
dc: docker compose
dcu: docker compose up -d
dcd: docker compose down
dcr: docker compose restart

# System
rmf: rm -rf
rmfast: FastDelete

ex: explorer
fix-next: rm -rf .next
fix-ports: sudo net stop winnat
fix-case-win: sudo fsutil file setCaseSensitiveInfo . enable recursive

"..": cd ..
"...": cd ../..
"....": cd ../../..
".....": cd ../../../..
