cursor-style = bar
window-padding-x = 6
confirm-close-surface = false

shell-integration = fish
command = /opt/homebrew/bin/fish -l

font-size = 14
adjust-cell-height = 35%

font-family = FiraCode Nerd Font
font-feature = +calt

background = #1E2227
foreground = #ABB2BF
cursor-color = #FFFFFF
selection-background = #FFFF00
selection-foreground = #000000
palette = 0=#4A4F5A
palette = 1=#EE5D69
palette = 2=#97C775
palette = 3=#B68353
palette = 4=#61AFEF
palette = 5=#C678DD
palette = 6=#56B6C2
palette = 7=#CCCCCC
palette = 8=#616A7B
palette = 9=#FE808A
palette = 10=#C2DEAD
palette = 11=#D1A47A
palette = 12=#93CFFF
palette = 13=#E0A8F1
palette = 14=#82D2DC
palette = 15=#FFFFFF

keybind = cmd+l=clear_screen
