theme = Atom One Dark
shell-integration = fish
command = /opt/homebrew/bin/fish -l

font-size = 14
adjust-cell-height = 35%

font-family = FiraCode Nerd Font
font-feature = +calt

cursor-style = bar
window-padding-x = 6

confirm-close-surface = false
