format = "$shell$shlvl$directory$git_branch$git_state$git_status$line_break$character"
follow_symlinks = false
add_newline = false


[shell]
disabled = false
format = "[$indicator ](dimmed) "
bash_indicator = ''
fish_indicator = ''
zsh_indicator = ''
cmd_indicator = ''
pwsh_indicator = ''

[shlvl]
disabled = false
format = '[\[$shlvl\]](dimmed red) '
threshold = 2


[directory]
style = "blue"


[git_branch]
format = "[$symbol ](dimmed)[$branch](yellow)"
symbol = ""

[git_status]
format = '[$all_status$ahead_behind](red)'
stashed = '[|](dimmed red)'
conflicted = "󰦎"
modified = "*"
renamed = "~"
behind = "↓"
ahead = "↑"
