#:schema https://developers.openai.com/codex/config-schema.json


model = "gpt-5.5"
model_reasoning_effort = "low"

personality = "pragmatic"
approval_policy = "never"


[windows]
sandbox = "elevated"


[features]
workspace_dependencies = false

[marketplaces.openai-bundled]
last_updated = "2026-05-02T09:18:49Z"
source_type = "local"
source = '\\?\C:\Users\Sayad\.codex\.tmp\bundled-marketplaces\openai-bundled'

[plugins."browser-use@openai-bundled"]
enabled = true
