opencode:
  models:
    - id: mimo-v2.5-free
    - id: nemotron-3-ultra-free
    - id: deepseek-v4-flash-free
      explore: true

# opencode-go:
#   models:
#     - id: glm-5.1
#     - id: kimi-k2.6
#     - id: minimax-m3
#     - id: mimo-v2.5-pro
#     - id: deepseek-v4-pro

openrouter:
  url: https://openrouter.ai/api/v1/models
  models:
    - id: openai/gpt-oss-120b
      title: true
    - id: moonshotai/kimi-k2.6
      options: { provider: { only: [fireworks] } }

# ollama-cloud:
#   models:
#     - id: minimax-m3

# openai:
#   models:
#     - id: gpt-5.5
#       context: 256000

xai:
  models:
    - id: grok-build-0.1

~agents:
  build:
    color: "#D2AE6B"
  plan:
    color: "#43ACB9"
  ask:
    color: "#89AE6E"
    permission:
      edit: deny
      task: deny
      todowrite: deny
  explore:
    color: "#ABB2BF"
    permission:
      edit: deny
      task: deny
      question: deny
      todowrite: deny
  general:
    color: "#D46870"
    disable: true
    permission:
      task: deny
      question: deny

  title:
    options:
      reasoning: { effort: medium }
      provider: { sort: throughput }
