openai:
  models:
    - id: gpt-5.5
      context: 272000
    - id: gpt-5.3-codex
      context: 272000

opencode:
  models:
    - minimax-m2.5-free

opencode-go:
  models:
    - glm-5
    - glm-5.1
    - kimi-k2.5
    - kimi-k2.6
    - mimo-v2-pro
    - mimo-v2.5-pro
    - deepseek-v4-pro
    - minimax-m2.7

# openrouter:
#   #  url: https://openrouter.ai/api/v1/models
#   models:
#     - id: openai/gpt-oss-120b
#       small: true
#       nitro: true
#       headers:
#         X-OpenRouter-Cache: "true"

# kilo:
#   #  url: https://api.kilo.ai/api/gateway/models
#   models:
#     - kilo-auto/free
#     - openrouter/free

fireworks-ai:
  models:
    - id: accounts/fireworks/models/gpt-oss-120b
      small: true
    # - id: accounts/fireworks/routers/kimi-k2p5-turbo
    #   small: true
