openai:
  models:
    - gpt-5.3-codex
    - id: gpt-5.4
      context: 128000

kilo:
  modelsURL: https://api.kilo.ai/api/gateway/models
  models:
    - kilo-auto/free

    - qwen/qwen3.6-plus

    - moonshotai/kimi-k2.5
    - moonshotai/kimi-k2.6

    - minimax/minimax-m2.5
    - minimax/minimax-m2.7

    - z-ai/glm-5.1
    - z-ai/glm-5-turbo
    - z-ai/glm-5v-turbo
