openrouter:
  url: https://openrouter.ai/api/v1/models
  models:
    - id: stealth/ox-alpha
    - id: openai/gpt-oss-120b
      title: true

opencode:
  models:
    - id: x-preview-f-free
    # - id: deepseek-v4-flash-free

openai:
  models:
    - id: gpt-5.6-sol
      context: 256000
    - id: gpt-5.6-terra
      context: 256000
    - id: gpt-5.6-luna
      context: 256000

~agents:
  build:
    color: "#C18A57"
  plan:
    color: "#43ACB9"
    permission:
      edit: deny
  general:
    color: "#D46870"
    permission:
      task: deny
      question: deny
  explore:
    color: "#ABB2BF"
    permission:
      edit: deny
      task: deny
      question: deny
  title:
    options:
      reasoning: { effort: medium }
      provider: { sort: throughput }
