opencode:
  models:
    - id: deepseek-v4-flash-free
      small: true
      explore: true

openrouter:
  url: https://openrouter.ai/api/v1/models
  models:
    - id: openai/gpt-oss-120b
      title: true
    - id: moonshotai/kimi-k2.6
    - id: deepseek/deepseek-v4-pro

# opencode-go:
#   models:
#     - id: glm-5.1
#     - id: kimi-k2.6
#     - id: mimo-v2.5-pro
#     - id: deepseek-v4-pro

# openai:
#   models:
#     - id: gpt-5.5
#       context: 256000
#     - id: gpt-5.3-codex
#       context: 256000

xai:
  models:
    - id: grok-build-0.1

crof:
  models:
    - id: kimi-k2.6
    - id: mimo-v2.5-pro
    - id: deepseek-v4-pro

~agents:
  general:
    permission: { lsp: deny, task: deny, question: deny }
  explore:
    permission:
      { lsp: deny, edit: deny, write: deny, task: deny, question: deny }
  title:
    options:
      reasoning: { effort: low }
      provider: { sort: throughput }
