msys2:
  - bash
  - fish

scoop:
  # Development Tools
  - gcc
  - scc
  - shfmt
  - extras/fvm
  - extras/tableplus

  - gh
  - aws
  - cloudflared

  # AI Coding Tools
  - codex
  - claude-code
  - extras/opencode-desktop

  # LLM Tools 
  - whisper-cpp
  - versions/llama.cpp-cpu

  # Visualization Tools
  - extras/onefetch
  - extras/hwinfo
  - wakatime-cli
  - fastfetch
  - hyperfine
  - btop
  - ntop

  # Shells
  - mise
  - gsudo
  - direnv
  - zoxide
  - starship

  # System Tools
  - nircmd

  # File System Tools
  - ripgrep
  - byenow
  - yazi
  - unzip
  - dust
  - eza
  - zip
  - fzf
  - rip
  - bat
  - lsd
  - fd
  - jq
  - yq

  # Workflow Tools
  - just
  - make
  - cmake

  # Media Tools
  - extras/anyburn
  - extras/winrar
  - extras/sharex
  - imagemagick
  - ffmpeg
  - yt-dlp
  - pandoc

  # Communication Tools
  - extras/slack

  # Misc
  - nerd-fonts/FiraCode-NF
  - extras/vcredist2022

winget:
  # Most Important
  - stax76.run-hidden
  - id: Git.Git
    name: Git
    interactiveInstall: true
  - id: Piriform.CCleaner
    name: CCleaner
    version: "6.39"
    interactiveInstall: true
    interactiveUpgrade: true

  # Windows Tools
  - id: 9N0DX20HK701
    name: Windows Terminal
  - id: 9MZ1SNWT0N5D
    name: PowerShell (pwsh)
  - id: 9MSMLRH6LZF3
    name: Windows Notepad
  - id: 9WZDNCRFHVN5
    name: Windows Calculator

  # Internet
  - Google.Chrome
  - Tonec.InternetDownloadManager
  - qBittorrent.qBittorrent

  # Media Tools
  - OBSProject.OBSStudio
  - ThioJoe.SvgThumbnailExtension
  - id: 9NBLGGH68TW4
    name: Pictureflect Photo Viewer
  - id: Daum.PotPlayer
    name: PotPlayer
    interactiveInstall: true
    interactiveUpgrade: true

  # Shells & Development Tools
  - id: MSYS2.MSYS2
    name: MSYS2
    skipInstall: true
    forceAdminInstall: true
    forceAdminUpgrade: true
  - id: LLVM.LLVM
    name: LLVM
    version: 21.1.8
    skipInstall: true

  # Others
  - RamenSoftware.Windhawk
  - UnifiedIntents.UnifiedRemote

  # Code Editors
  - id: 9PLM9XGG6VKS
    name: Codex App
  - id: Microsoft.VisualStudioCode
    name: VSCode
    scope: User
    interactiveInstall: true

  # DotNet SDKs
  - Microsoft.DotNet.SDK.6
  - Microsoft.DotNet.SDK.7
  - Microsoft.DotNet.SDK.8
  - Microsoft.DotNet.SDK.9

  # VM & Container Tools
  - id: Docker.DockerDesktop
    name: Docker Desktop
    forceAdminInstall: true
    forceAdminUpgrade: true
    interactiveInstall: true
