# Shell
brew "zsh"
brew "bash"
brew "fish"

# Terminal or Shell Tools
brew "btop"
brew "zoxide"
brew "direnv"
brew "starship"
cask "ghostty"

# System
brew "libomp"
brew "mole"
brew "batt", restart_service: true

# Internet
brew "wget"
cask "localsend"
cask "google-chrome"

# File System
brew "zip"
brew "unzip"
brew "p7zip"
brew "7-zip"
brew "ripgrep"

# Media
cask "vlc"
cask "obs"
brew "ffmpeg"
brew "imagemagick"

# Productivity
cask "raycast"
cask "unified-remote"
cask "karabiner-elements"

# Cloud
brew "awscli"

# Git
brew "git"
brew "git-lfs"
brew "git-delta"
brew "gnupg"

# Development
cask "visual-studio-code"
brew "shfmt"
brew "mise"
brew "fvm"

# Docker
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"

# Fonts
cask "font-fira-code-nerd-font"
cask "font-ibm-plex-sans"
