# Dependencies
brew "re2c"
brew "icu4c"
brew "readline"
brew "bison", link: true
brew "libomp"
brew "libzip"
brew "libiconv"
brew "libsodium"
brew "pkgconf"
brew "autoconf"
brew "pkg-config"

# Shell
brew "zsh"
brew "bash"
brew "fish"

# CLI Tools
brew "btop"
brew "zoxide"
brew "direnv"
brew "starship"

# Terminal
cask "ghostty"

# System
brew "mole"
brew "batt"
cask "hammerspoon"

# Browsers
cask "google-chrome"
cask "helium-browser"
cask "zen"

# Internet
brew "wget"
cask "localsend"
cask "protonvpn"
cask "free-download-manager"

# File System
brew "zip"
brew "unzip"
brew "p7zip"
brew "7-zip"
brew "ripgrep"

# Media
cask "vlc"
cask "obs"
brew "ffmpeg"
brew "imagemagick"

# Productivity
cask "raycast"
cask "unified-remote"
cask "karabiner-elements"

# Cloud
brew "cloudflared"

# Git
brew "git"
brew "git-lfs"
brew "git-delta"
brew "gnupg"

# AI & Code Editors
cask "visual-studio-code@insiders"
cask "visual-studio-code"

# Development
cask "tablepro"
brew "shfmt"
brew "fvm"

# Docker
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"

# Fonts
cask "font-fira-code-nerd-font"
cask "font-ibm-plex-sans"
