# Shell
brew "zsh"
brew "bash"
brew "fish"
brew "btop"
brew "zoxide"
brew "direnv"
brew "starship"
cask "ghostty"

# System
brew "libomp"
brew "batt", restart_service: true

# Internet
brew "wget"
cask "google-chrome"

# File System
brew "zip"
brew "unzip"
brew "p7zip"
brew "7-zip"
brew "ripgrep"

# Media
cask "obs"

# Productivity
cask "raycast"
cask "unified-remote"
cask "karabiner-elements"

# Cloud
brew "awscli"
brew "cloudflared"

# Git
brew "git"
brew "git-lfs"
brew "git-delta"
brew "gnupg"

# Development
cask "visual-studio-code"
cask "postman"
brew "shfmt"
brew "mise"
brew "fvm"

# AI Coding
tap "anomalyco/tap"
brew "anomalyco/tap/opencode"
cask "claude-code"
cask "codex"

# Docker
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"

# Fonts
cask "font-fira-code-nerd-font"
cask "font-ibm-plex-sans"
