opencode-openai:
  - credential: "Work"
    model: "gpt-6-luna"
    minDuration: 30
  - credential: "Sayad"
    model: "gpt-6-luna"
    minDuration: 1440

claude:
  - dir: "~/.claude-extra"
    model: "claude-haiku-5-5"
    minDuration: 30
