[tools]

# JS/TS
node = "lts"
bun = "latest"
deno = "latest"

"npm:pnpm" = "latest"
"npm:taze" = "latest"
"npm:@antfu/ni" = "latest"

"npm:tsx" = "latest"
"npm:jiti" = "latest"


# Python
uv = "latest"
python = "latest"


# GO
go = "latest"
gofumpt = "latest"
"go:golang.org/x/tools/gopls" = "latest"


# Rust
rust = "stable"
rust-analyzer = "latest"


# Mobile Apps
dart = "latest"
java = "latest"
# kotlin = "latest"


# php = "latest"
# zig = "latest"
# ruby = "latest"
# "conda:lua" = "latest"
# "conda:luajit" = "latest"


# CLI Tools
"npm:gityo" = "latest"
"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:openusage" = "latest"
"npm:git-stats" = "latest"
"npm:npm-name-cli" = "latest"

# MCP
"npm:chrome-devtools-mcp" = "latest"
"npm:@hugeicons/mcp-server" = "latest"


# Cloud Tools
gcloud = "latest"
firebase = "latest"


# System Tools
"cargo:shaka" = "latest"

[settings]
auto_install = false
exec_auto_install = true
not_found_auto_install = true
