#:schema https://mise.jdx.dev/schema/mise.json

[tools]

# Git
gh = "latest"
glab = "latest"
lazygit = "latest"
"github:unhappychoice/gitlogue" = "latest"
"github:JoaoOliveira889/monogit" = "latest"

# System
cmake = "latest"
"cargo:dotsh" = "latest"
"cargo:shaka" = "latest"
"aqua:Songmu/timeout" = "latest"

# File System
jq = "latest"
yq = "latest"
fd = "latest"
bat = "latest"
lsd = "latest"
fzf = "latest"
dust = "latest"
yazi = "latest"

# Activities
fastfetch = "latest"
"github:wakatime/wakatime-cli" = "latest"

# Workflow
just = "latest"
make = "latest"
ninja = "latest"

# AI Coding
"github:openai/codex" = "latest"
"github:earendil-works/pi" = "latest"
"github:anomalyco/opencode" = "latest"
"github:anthropics/claude-code" = "latest"

# JS/TS
node = "lts"
bun = "latest"
deno = "latest"
pnpm = "latest"
"npm:tsx" = "latest"
"npm:taze" = "latest"
"npm:@antfu/ni" = "latest"

# Python
uv = "latest"
python = "latest"

# GO
go = "latest"
air = "latest"
gofumpt = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"github:golangci/golangci-lint" = "latest"

# Rust
rust = "stable"
rust-analyzer = "latest"

# Others
java = "latest"
# dart = "latest"
# kotlin = "latest"
# php = "latest"
# zig = "latest"
# ruby = "latest"
# "conda:lua" = "latest"
# "conda:luajit" = "latest"

# Dev
sqlite = "latest"
hyperfine = "latest"
lazydocker = "latest"
"npm:prettier" = "latest"
"npm:concurrently" = "latest"
"github:boyter/scc" = "latest"

# Web
"npm:serve" = "latest"
"npm:live-server" = "latest"

# AI
"npm:skills" = "latest"
"npm:devrage" = "latest"
"npm:mysubs" = "latest"
"npm:mytokens" = "latest"

# Personal
"npm:gityo" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:create-src" = "latest"
"npm:opencode-armor" = "latest"

# MCP
"npm:chrome-devtools-mcp" = "latest"

# Others
"npm:@schpet/linear-cli" = "latest"
yt-dlp = "latest"


[settings.npm]
package_manager = "pnpm"

[settings]
auto_install = false
exec_auto_install = true
not_found_auto_install = true
trusted_config_paths = ["~/Desktop"]

minimum_release_age_excludes = [
  # Runtime
  "uv",
  "bun",
  "node",
  "deno",
  "pnpm",

  # AI Coding
  "github:openai/codex",
  "github:earendil-works/pi",
  "github:anomalyco/opencode",
  "github:anthropics/claude-code",

  # My Tools
  "npm:gityo",
  "npm:netserv",
  "npm:uni-run",
  "npm:mysubs",
  "npm:mytokens",
  "npm:create-src",
  "npm:opencode-armor",
]
