[tools]

# JS/TS
node = "lts"
bun = "latest"
deno = "latest"

"npm:yarn" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

"npm:tsx" = "latest"
"npm:jiti" = "latest"
"npm:taze" = "latest"


# Python
uv = "latest"
python = "latest"


# GO
go = "latest"
gofumpt = "latest"
"go:golang.org/x/tools/gopls" = "latest"


# Rust
rust = "stable"
rust-analyzer = "latest"


# php = "latest"
# zig = "latest"
# java = "latest"
# ruby = "latest"
# kotlin = "latest"
# "conda:lua" = "latest"
# "conda:luajit" = "latest"


# CLI Tools
"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:code-info" = "latest"
"npm:git-stats" = "latest"
"npm:npm-name-cli" = "latest"


# Google Cloud Tools
gcloud = "latest"
"npm:firebase-tools" = "latest"


[settings]
experimental = true
