#:schema https://mise.jdx.dev/schema/mise.json

[tools]

# System Tools
cmake = "latest"
"cargo:dotsh" = "latest"
"cargo:shaka" = "latest"
"cargo:pwshac" = "latest"


# Workflow Tools
make = "latest"
just = "latest"


# JS/TS
node = "lts"
bun = "latest"
deno = "latest"
"npm:tsx" = "latest"
"npm:pnpm" = "latest"
"npm:taze" = "latest"
"npm:@antfu/ni" = "latest"


# Python
uv = "latest"
python = "latest"


# GO
go = "latest"
gofumpt = "latest"
"go:golang.org/x/tools/gopls" = "latest"


# Rust
rust = "stable"
rust-analyzer = "latest"


# Mobile Apps
java = "latest"
# dart = "latest"
# kotlin = "latest"


# php = "latest"
# zig = "latest"
# ruby = "latest"
# "conda:lua" = "latest"
# "conda:luajit" = "latest"


# CLI Tools
"npm:gityo" = "latest"

"npm:code-info" = "latest"
"npm:openusage" = "latest"
"npm:git-stats" = "latest"

"npm:serve" = "latest"
"npm:netserv" = "latest"
"npm:uni-run" = "latest"
"npm:live-server" = "latest"

# MCP
"npm:chrome-devtools-mcp" = "latest"
"npm:@hugeicons/mcp-server" = "latest"


# Cloud Tools
gcloud = "latest"
firebase = "latest"


[settings]
experimental = true

env_file = ".env"
env_shell_expand = true

auto_install = false
exec_auto_install = true
not_found_auto_install = true

trusted_config_paths = ["~/Desktop"]
