# Development Tools
- gcc
- scc
- shfmt
- extras/fvm

- gh
- aws
- ngrok

# AI Tools
- codex
- extras/opencode-desktop

# Visualization Tools
- extras/hwinfo
- fastfetch
- hyperfine
- btop
- ntop

# Shells
- mise
- gsudo
- direnv
- zoxide
- starship

# System Tools
- nircmd

# File System Tools
- ripgrep
- byenow
- yazi
- fzf
- rip
- dust
- bat
- lsd
- fd

# Workflow Tools
- make
- just
- cmake
- llvm

# Media Tools
- extras/anyburn
- extras/winrar
- extras/sharex
- imagemagick
- ffmpeg
- yt-dlp

# Fonts
- nerd-fonts/FiraCode-NF

# Communication Tools
- extras/slack
