opencode-cli:
  description: OpenCode CLI
  homepage: https://opencode.ai/

  bin:
    - - opencode.exe
      - opencode

  version:
    url: https://api.github.com/repos/anomalyco/opencode/releases/latest
    regex: "\"tag_name\"\\s*:\\s*\"v([^\"]+)\""

  autoupdate:
    architecture:
      64bit:
        url: https://github.com/anomalyco/opencode/releases/download/v$version/opencode-windows-x64.zip

opencode-tauri:
  description: OpenCode desktop app
  homepage: https://opencode.ai/

  install:
    - Remove-Item "$dir\`$*", "$dir\Uninstall*" -Force -Recurse -ErrorAction
      Ignore

  shortcuts:
    - - OpenCode.exe
      - OpenCode (Tauri)

  version:
    url: https://api.github.com/repos/anomalyco/opencode/releases/latest
    regex: "\"tag_name\"\\s*:\\s*\"v([^\"]+)\""

  autoupdate:
    architecture:
      64bit:
        url: https://github.com/anomalyco/opencode/releases/download/v$version/opencode-desktop-windows-x64.exe#/dl.7z

opencode-electron:
  description: OpenCode Electron app
  homepage: https://opencode.ai/

  extract: $PLUGINSDIR
  install:
    - Expand-7zipArchive (Join-Path $dir 'app-64.7z') (Join-Path $dir 'app')

  shortcuts:
    - - app/OpenCode.exe
      - OpenCode (Electron)

  version:
    url: https://api.github.com/repos/anomalyco/opencode/releases/latest
    regex: "\"tag_name\"\\s*:\\s*\"v([^\"]+)\""

  autoupdate:
    architecture:
      64bit:
        url: https://github.com/anomalyco/opencode/releases/download/v$version/opencode-electron-win-x64.exe#/dl.7z

t3code:
  description: T3 Code desktop app
  homepage: https://github.com/pingdotgg/t3code

  extract: $PLUGINSDIR
  install:
    - Expand-7zipArchive (Join-Path $dir 'app-64.7z') (Join-Path $dir 'app')

  bin:
    - - app/T3 Code (Alpha).exe
      - t3code
  shortcuts:
    - - app/T3 Code (Alpha).exe
      - T3 Code

  version:
    url: https://api.github.com/repos/pingdotgg/t3code/releases?per_page=100
    regex: "\"tag_name\"\\s*:\\s*\"v([^\"]+)\""

  autoupdate:
    architecture:
      64bit:
        url: https://github.com/pingdotgg/t3code/releases/download/v$version/T3-Code-$version-x64.exe#/dl.7z
