# Development Tools
- gcc
- scc
- shfmt
- extras/fvm

- gh
- aws
- cloudflared

# AI Tools
- whisper-cpp
- versions/llama.cpp-cpu
- extras/opencode-desktop

# Visualization Tools
- extras/onefetch
- extras/hwinfo
- fastfetch
- hyperfine
- btop
- ntop

# Shells
- mise
- gsudo
- direnv
- zoxide
- starship

# System Tools
- nircmd

# File System Tools
- ripgrep
- byenow
- yazi
- unzip
- zip
- fzf
- rip
- dust
- bat
- lsd
- fd

# Workflow Tools
- make
- just

# Media Tools
- extras/anyburn
- extras/winrar
- extras/sharex
- imagemagick
- ffmpeg
- yt-dlp

# Fonts
- nerd-fonts/FiraCode-NF
- nerd-fonts/JetBrainsMono-NF

# Communication Tools
- extras/slack
