# Shell
"@/config/shell/bashrc.sh": "~/.bashrc"
"@/config/shell/fishrc.fish": "~/.config/fish/config.fish"
"@/config/shell/pwshrc.ps1":
  Win: "~/Documents/PowerShell/profile.ps1"
"@/config/shell/profile.sh":
  Mac: "~/.bash_profile"

# Agents Skills
"@/agents/skills":
  - "~/.claude/skills"
  - "~/.gemini/antigravity-cli/skills"

# AGENTS.md
"@/agents/AGENTS_MD.md":
  - "~/.gemini/GEMINI.md"
  - "~/.claude/CLAUDE.md"
  - "~/.config/opencode/AGENTS.md"

# Claude Code
"@/agents/claude.json":
  - "~/.claude/settings.json"

# OpenCode
"@/agents/opencode/plugins": "~/.config/opencode/plugins"
"@/agents/opencode/sounds": "~/.config/opencode/sounds"
"@/agents/opencode/themes": "~/.config/opencode/themes"
"@/agents/opencode/ext.json": "~/.opencode-ext.json"

# OpenCode Desktop
"@/agents/opencode/desktop.dat":
  Win.Copy: "$APPDATA/ai.opencode.desktop/default.dat"
  Mac.Copy: "~/Library/Application Support/ai.opencode.desktop/default.dat"

# Terminal
"@/config/shell/alias.json": "~/.config/shaka/config.json"
"@/config/shell/starship.toml": "~/.config/starship.toml"
"@/config/shell/direnv.toml": "~/.config/direnv/direnv.toml"
"@/config/mise-config.toml": "~/.config/mise/config.toml"
"@/config/shell/fastfetch-win.jsonc":
  Win: "~/.config/fastfetch/config.jsonc"
"@/config/shell/fastfetch-mac.jsonc":
  Mac: "~/.config/fastfetch/config.jsonc"
"@/config/shell/btop.conf": "~/.config/btop/btop.conf"
"@/config/shell/lsd-config.yaml": "~/.config/lsd/config.yaml"

# Terminal Emulators
"@/config/shell/ghostty.conf":
  Mac: "~/.config/ghostty/config"
"@/config/shell/cmux.json":
  Mac.Copy: "~/.config/cmux/cmux.json"
"@/config/windows-terminal.json":
  Win: "$LOCALAPPDATA/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

# OBS
"@/config/obs/basic-win":
  Win.Copy: "$APPDATA/obs-studio/basic"
"@/config/obs/user-win.ini":
  Win.Copy: "$APPDATA/obs-studio/user.ini"
"@/config/obs/basic-mac":
  Mac.Copy: "~/Library/Application Support/obs-studio/basic"
"@/config/obs/user-mac.ini":
  Mac.Copy: "~/Library/Application Support/obs-studio/user.ini"

# Git
"@/config/global.gitignore": "~/.gitignore"
"@/config/monogit.json":
  Win.Copy: "$APPDATA/monogit/config.json"
  Mac.Copy: "~/Library/Application Support/monogit/config.json"

# Other
"@/config/colima.yaml":
  Mac.Copy: "~/.colima/default/colima.yaml"
"@/config/docker-mac.json":
  Mac.Copy: "~/.docker/config.json"
"@/config/pnpm.yaml":
  Win: "$LOCALAPPDATA/pnpm/config.yaml"
  Mac: "~/Library/Preferences/pnpm/config.yaml"
"@/config/oiper.json":
  Win: "$APPDATA/com.oiper.desktop/config.json"
  Mac: "~/Library/Application Support/com.oiper.desktop/config.json"
"@/config/uni-run.json": "~/.uni-run.json"
"@/config/mysubs.json": "~/.config/mysubs/config.json"
"@/config/mytokens-group.json": "~/.mytokens/groups.json"
"@/config/cloudflared.yml": "~/.cloudflared/config.yml"
"@/config/gityo.json": "~/.config/gityo.json"
"@/config/nirc": "~/.nirc"

# System
"@/config/Windhawk.json":
  Win: "$PROGRAMDATA/Windhawk/userprofile.json"
"@/config/hammerspoon.lua":
  Mac: "~/.hammerspoon/init.lua"
"@/config/US Simplified.keylayout":
  Mac.Copy: "~/Library/Keyboard Layouts/US Simplified.keylayout"

# Private
"$SYSTEM_FILE_DIR/AIMP":
  Win: "$APPDATA/AIMP"
"$SYSTEM_FILE_DIR/WinRar.ini":
  Win: "~/scoop/apps/winrar/current/WinRar.ini"
"$SYSTEM_FILE_DIR/qBittorrent.ini":
  Win.Copy: "$APPDATA/qBittorrent/qBittorrent.ini"

# Code Editor
"@/config/vscode/snippets":
  Win:
    - "$APPDATA/Code/User/snippets"
    - "$APPDATA/Code - Insiders/User/snippets"
  Mac:
    - "~/Library/Application Support/Code/User/snippets"
    - "~/Library/Application Support/Code - Insiders/User/snippets"
"@/config/vscode/settings.jsonc":
  Win:
    - "$APPDATA/Code/User/settings.json"
    - "$APPDATA/Code - Insiders/User/settings.json"
  Mac:
    - "~/Library/Application Support/Code/User/settings.json"
    - "~/Library/Application Support/Code - Insiders/User/settings.json"
"@/config/vscode/keybindings.jsonc":
  Win:
    - "$APPDATA/Code/User/keybindings.json"
    - "$APPDATA/Code - Insiders/User/keybindings.json"
"@/config/vscode/mac-keybindings.jsonc":
  Mac:
    - "~/Library/Application Support/Code/User/keybindings.json"
    - "~/Library/Application Support/Code - Insiders/User/keybindings.json"
