alias c="gh repo clone"
alias gv="gh repo view"
alias gw="gh repo view --web"

alias gp="git pull"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"

alias n="npm run"
alias nx="npm exec"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nu="npm uninstall"
alias nup="npm update"

alias p="pnpm run"
alias px="pnpm dlx"
alias pim="pnpm import"
alias pa="pnpm add"
alias pad="pnpm add --save-dev"
alias pi="pnpm install"
alias pr="pnpm remove"
alias pup="pnpm update"