alias c="gh repo clone"
alias gv="gh repo view"
alias gw="gh repo view --web"

alias gp="git pull"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"

alias r="npm run"
alias nx="npm exec"
alias np="npm prune"
alias ni="npm install --save"
alias nid="npm install --save-dev"
alias nu="npm uninstall --save"
alias nup="npm update --save"